sudo: required
dist: trusty
language: node_js

node_js:
  - "6"
  - "7"
  - "8"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - jq
      - shellcheck
      - moreutils

cache:
  directories:
    - node_modules

before_install:

install:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew update; brew cleanup; brew cask cleanup; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew uninstall --force brew-cask; brew update; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install moreutils; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install shellcheck; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install jq; fi
  - npm install

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - shellcheck bin/*.sh
  - npm run test:linux
  - npm run test:npm && echo 'Npm packing test is passed'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change

after_success:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then npm run coverage; fi

before_deploy:
  - npm version
  - npm run dist

deploy:
  provider: npm
  email: zixia@zixia.net
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
