version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: info
          command: |
            docker --version
            docker info
            whoami
      - run:
          name: setup
          command: |
            apk update && apk add curl curl-dev
            curl -sSL -o /tmp/bats_v0.4.0.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
            tar -xf /tmp/bats_v0.4.0.tar.gz
            bats-0.4.0/install.sh /usr/local
      - run:
          name: build
          command: |
            docker run -ti -v "$(pwd)":/mnt nlknguyen/alpine-shellcheck bin/*.sh
            ./script/docker.sh build
      - run:
          name: test
          command: |
            ./script/docker.sh test
      - deploy:
          command: |
            curl -X POST -d '{"from":"circleci"}' "$DOCKER_REBUILD_URL"
