version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: info
          command: |
            docker --version
            docker info
            whoami
      - run:
          name: setup
          command: |
            apk update
            apk install bats
            apt-get update -qq
            sudo apt-get install -y -qq software-properties-common

            sudo add-apt-repository ppa:duggan/bats --yes
            sudo apt-get update -qq
            sudo apt-get install -y -qq bats

      - run:
          name: build
          command: |
            docker run -ti -v "$(pwd)":/mnt nlknguyen/alpine-shellcheck bin/*.sh
            ./script/docker.sh build
      - run:
          name: test
          command: |
            ./script/docker.sh test
      - deploy:
          command: |
            curl -X POST -d '{"from":"circleci"}' "$DOCKER_REBUILD_URL"
