version: 2

jobs:
  build:
    steps:
      - checkout
      - run: whoami
      - run: sudo add-apt-repository ppa:duggan/bats --yes
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -qq bats
      - run: docker --version
      - run: docker info
      - run: docker run -ti -v "$(pwd)":/mnt nlknguyen/alpine-shellcheck bin/*.sh
      - run: ./script/docker.sh build
  test:
    steps:
      - run: ./script/docker.sh test

  deploy:
    branch: master
    steps:
      - run: curl -X POST -d '{"from":"circleci"}' "$DOCKER_REBUILD_URL"

workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
