version: 2

jobs:
  build:
    docker:
      - image: ubuntu:17.04

    steps:
      - checkout
      - run:
          name: setup
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y -qq software-properties-common

            sudo add-apt-repository ppa:duggan/bats --yes
            sudo apt-get update -qq
            sudo apt-get install -y -qq bats

            docker --version
            docker info
      - run:
          name: build
          command: |
            docker run -ti -v "$(pwd)":/mnt nlknguyen/alpine-shellcheck bin/*.sh
            ./script/docker.sh build
      - run:
          name: test
          command: |
            ./script/docker.sh test
      - deploy:
          command: |
            curl -X POST -d '{"from":"circleci"}' "$DOCKER_REBUILD_URL"
